/* ============================================================
   BĒSIA, sw.js   (generated by tools/build-sw.js, do not edit)

   Keeps the website and the Studio Manager working when the power
   or the network goes. Regenerated on every build.
   ============================================================ */
const VERSION = '19ca0305';
const CACHE = 'besia-' + VERSION;

const PRECACHE = [
  "./",
  "404.html",
  "assets/icons/favicon.svg",
  "css/issue.css",
  "fonts/montserrat-latin-ext.woff2",
  "fonts/montserrat-latin.woff2",
  "fonts/montserrat-macron.woff2",
  "index.html",
  "js/besia-data.js",
  "js/besia-live.js",
  "js/booking-cart.js",
  "js/booking.js",
  "js/offline.js",
  "js/reel.js",
  "js/site-sync.js",
  "js/site.js",
  "js/slides.js",
  "js/store.js",
  "offline.html"
];

/* The Studio Manager's shell, fetched into the cache the first time an
   admin page is opened, never on the public site. */
const ADMIN = [
  "admin/activity.html",
  "admin/balances.html",
  "admin/bookings.html",
  "admin/cash.html",
  "admin/classes.html",
  "admin/clients.html",
  "admin/dashboard.html",
  "admin/discounts.html",
  "admin/expenses.html",
  "admin/help.html",
  "admin/orders.html",
  "admin/payments.html",
  "admin/prices.html",
  "admin/reports.html",
  "admin/sales.html",
  "admin/sell.html",
  "admin/settings.html",
  "admin/staff.html",
  "admin/stock.html",
  "admin/suppliers.html",
  "css/admin.css",
  "js/admin-ask.js",
  "js/admin-catalogue.js",
  "js/admin-pages.js",
  "js/admin.js"
];
const IMAGE_CACHE_MAX = 80;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One failed file must not fail the whole install. */
      .then(c => Promise.allSettled(PRECACHE.map(url => c.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('besia-') && !k.startsWith('besia-classic-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  if (e.data === 'skip-waiting') self.skipWaiting();
});

/* Photographs are cached as they are seen; keep the newest eighty so
   the cache cannot grow without limit on a phone. */
function trimImages(c) {
  return c.keys().then(keys => {
    const imgs = keys.filter(k => /\.(webp|jpe?g|png|gif|avif)$/i.test(new URL(k.url).pathname));
    const extra = imgs.length - IMAGE_CACHE_MAX;
    return extra > 0 ? Promise.all(imgs.slice(0, extra).map(k => c.delete(k))) : null;
  });
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* fonts and CDNs handle themselves */

  /* Films are never answered here. Safari asks for them in byte ranges
     and expects 206 replies; a cached full 200 breaks playback. They
     are also the heaviest thing on the site, not worth a cache slot. */
  if (req.headers.has('range') || /\.(mp4|webm)$/i.test(url.pathname)) return;

  /* Pages: try the network so a fresh deploy is picked up, fall back to
     the cache when there is nothing to reach. */
  if (req.mode === 'navigate') {
    if (/\/admin\//.test(url.pathname)) {
      event.waitUntil(caches.open(CACHE).then(c => c.keys().then(keys => {
        const have = new Set(keys.map(k => new URL(k.url).pathname));
        const missing = ADMIN.filter(f => !have.has(new URL(f, self.location.href).pathname));
        return Promise.allSettled(missing.map(f => c.add(f)));
      })));
    }
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match('./offline.html')))
    );
    return;
  }

  /* Code and styles: network first, cache as the fallback.
     Serving a stale script against a fresh page is worse than a few
     hundred milliseconds of latency, it means a deploy lands with the
     new HTML calling into the old JavaScript, and buttons quietly stop
     working. These files are small; correctness wins. */
  if (/\.(js|css)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  /* Everything else, images, icons, fonts, is heavy and rarely changes,
     so serve it from cache instantly and refresh in the background. */
  event.respondWith(
    caches.match(req).then(hit => {
      const net = fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy).then(() => trimImages(c)));
          }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});
