/* ============================================================
   BĒSIA — sw.js   (generated by tools/build-sw.js — do not edit)

   Keeps the website and the Studio Manager working when the power
   or the network goes. Regenerated on every build.
   ============================================================ */
const VERSION = '0f155822';
const CACHE = 'besia-' + VERSION;

const PRECACHE = [
  "./",
  "404.html",
  "about.html",
  "admin/activity.html",
  "admin/balances.html",
  "admin/bookings.html",
  "admin/cash.html",
  "admin/classes.html",
  "admin/clients.html",
  "admin/dashboard.html",
  "admin/discounts.html",
  "admin/expenses.html",
  "admin/help.html",
  "admin/orders.html",
  "admin/payments.html",
  "admin/prices.html",
  "admin/reports.html",
  "admin/sales.html",
  "admin/sell.html",
  "admin/settings.html",
  "admin/staff.html",
  "admin/stock.html",
  "admin/suppliers.html",
  "assets/icons/favicon.svg",
  "checkout.html",
  "classes.html",
  "contact.html",
  "css/admin.css",
  "css/animations.css",
  "css/style.css",
  "gallery.html",
  "index.html",
  "js/admin-ask.js",
  "js/admin-catalogue.js",
  "js/admin-pages.js",
  "js/admin.js",
  "js/ai-chat.js",
  "js/animations.js",
  "js/besia-data.js",
  "js/besia-live.js",
  "js/booking.js",
  "js/classes.js",
  "js/gallery.js",
  "js/main.js",
  "js/offline.js",
  "js/site-sync.js",
  "js/store.js",
  "offline.html",
  "packages.html",
  "services.html",
  "shop.html",
  "track.html",
  "images/studio/studio-reception.jpg",
  "images/studio/studio-nook.jpg",
  "images/studio/studio-wash.jpg",
  "images/studio/studio-corner.jpg",
  "images/studio/studio-branding.jpg"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One failed file must not fail the whole install. */
      .then(c => Promise.allSettled(PRECACHE.map(url => c.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  if (e.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* fonts and CDNs handle themselves */

  /* Pages: try the network so a fresh deploy is picked up, fall back to
     the cache when there is nothing to reach. */
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match('./offline.html')))
    );
    return;
  }

  /* Code and styles: network first, cache as the fallback.
     Serving a stale script against a fresh page is worse than a few
     hundred milliseconds of latency — it means a deploy lands with the
     new HTML calling into the old JavaScript, and buttons quietly stop
     working. These files are small; correctness wins. */
  if (/.(js|css)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  /* Everything else — images, icons, fonts — is heavy and rarely changes,
     so serve it from cache instantly and refresh in the background. */
  event.respondWith(
    caches.match(req).then(hit => {
      const net = fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});
