/* ============================================================
   build-css.js, joins css/issue/*.css into one css/issue.css.

   Order matters and is fixed: tokens, base, components, templates,
   pages. One file, one request, cached by the service worker. No
   minifier: the sources are already plain, and a readable shipped
   file is worth more than a few kilobytes to whoever inherits this.

   Run:  node tools/build-css.js   (build-all does this for you)
   ============================================================ */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'css', 'issue');
const ORDER = ['tokens.css', 'base.css', 'components.css', 'templates.css', 'pages.css'];

let out = '/* BĒSIA, THE ISSUE: generated by tools/build-css.js from css/issue/, do not edit here */\n';
let bytes = 0;
for (const f of ORDER) {
  const p = path.join(SRC, f);
  if (!fs.existsSync(p)) continue;
  const css = fs.readFileSync(p, 'utf8');
  bytes += css.length;
  out += '\n/* ==== ' + f + ' ==== */\n' + css.trim() + '\n';
}
fs.writeFileSync(path.join(ROOT, 'css', 'issue.css'), out);
console.log('css/issue.css written, ' + Math.round(out.length / 1024) + ' KB from ' + ORDER.filter(f => fs.existsSync(path.join(SRC, f))).length + ' files.');
