/* ============================================================
   build-sw.js — writes sw.js, the offline service worker.

   Why this matters here: power and data are not guaranteed in
   Accra. If the lights go or the network drops mid-appointment,
   the Studio Manager has to keep working — the owner is holding
   somebody's money. Everything is already in the browser, so the
   only thing missing was the files themselves.

   The shell (pages, CSS, JS, icons) is precached on first visit.
   Photographs are cached as they are seen, so the first load
   stays light on a metered connection.

   Run:  node tools/build-sw.js   (build-all does this for you)
   ============================================================ */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (['.git', 'node_modules', '.claude', 'tools', 'images'].includes(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
}

const shell = walk(ROOT)
  .map(p => path.relative(ROOT, p).split(path.sep).join('/'))
  .filter(f => /\.(html|css|js|svg|woff2)$/i.test(f))
  .filter(f => !f.startsWith('sw.js'))
  .sort();

/* The five studio photographs carry the hero on every page — worth
   having offline. The rest of the library is cached as it is browsed. */
const keyImages = [
  'images/studio/studio-reception.jpg',
  'images/studio/studio-nook.jpg',
  'images/studio/studio-wash.jpg',
  'images/studio/studio-corner.jpg',
  'images/studio/studio-branding.jpg'
].filter(f => fs.existsSync(path.join(ROOT, f)));

const precache = ['./'].concat(shell, keyImages);

/* A hash of the shell, so a deploy replaces the old cache rather than
   leaving somebody on a stale copy. */
const hash = crypto.createHash('sha1');
shell.forEach(f => hash.update(f + fs.statSync(path.join(ROOT, f)).size));
const version = hash.digest('hex').slice(0, 8);

const sw = `/* ============================================================
   BĒSIA — sw.js   (generated by tools/build-sw.js — do not edit)

   Keeps the website and the Studio Manager working when the power
   or the network goes. Regenerated on every build.
   ============================================================ */
const VERSION = '${version}';
const CACHE = 'besia-' + VERSION;

const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One failed file must not fail the whole install. */
      .then(c => Promise.allSettled(PRECACHE.map(url => c.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  if (e.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* fonts and CDNs handle themselves */

  /* Pages: try the network so a fresh deploy is picked up, fall back to
     the cache when there is nothing to reach. */
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match('./offline.html')))
    );
    return;
  }

  /* Code and styles: network first, cache as the fallback.
     Serving a stale script against a fresh page is worse than a few
     hundred milliseconds of latency — it means a deploy lands with the
     new HTML calling into the old JavaScript, and buttons quietly stop
     working. These files are small; correctness wins. */
  if (/\.(js|css)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  /* Everything else — images, icons, fonts — is heavy and rarely changes,
     so serve it from cache instantly and refresh in the background. */
  event.respondWith(
    caches.match(req).then(hit => {
      const net = fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('sw.js written — version ' + version + ', ' + precache.length + ' files precached.');
console.log('  (' + shell.length + ' shell files + ' + keyImages.length + ' studio photographs)');
