/* ============================================================
   build-sw.js, writes sw.js, the offline service worker.

   Why this matters here: power and data are not guaranteed in
   Accra. If the lights go or the network drops mid-appointment,
   the Studio Manager has to keep working, the owner is holding
   somebody's money. Everything is already in the browser, so the
   only thing missing was the files themselves.

   The shell (pages, CSS, JS, icons) is precached on first visit.
   Photographs are cached as they are seen, so the first load
   stays light on a metered connection.

   Run:  node tools/build-sw.js   (build-all does this for you)
   ============================================================ */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (['.git', 'node_modules', '.claude', 'tools', 'images'].includes(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
}

const all = walk(ROOT)
  .map(p => path.relative(ROOT, p).split(path.sep).join('/'))
  .filter(f => /\.(html|css|js|svg|woff2)$/i.test(f))
  .filter(f => !f.startsWith('sw.js') && !f.startsWith('media/') && !f.startsWith('js/vendor/') &&
               f !== 'styleguide.html' && !/\.(spec|test)\.js$/.test(f))
  .sort();
/* The public shell is precached on first visit. The Studio Manager's
   own pages and scripts are cached the first time the owner opens the
   manager, so a client browsing on mobile data never downloads it. */
const shell = all.filter(f => !f.startsWith('admin/') && !/^js\/admin/.test(f) && f !== 'css/admin.css');
const adminShell = all.filter(f => !shell.includes(f));

/* The five studio photographs carry the hero on every page, worth
   having offline. The rest of the library is cached as it is browsed. */
const keyImages = [].filter(f => fs.existsSync(path.join(ROOT, f)));

const precache = ['./'].concat(shell, keyImages);

/* A hash of the shell, so a deploy replaces the old cache rather than
   leaving somebody on a stale copy. */
const hash = crypto.createHash('sha1');
all.forEach(f => hash.update(f).update(fs.readFileSync(path.join(ROOT, f))));
const version = hash.digest('hex').slice(0, 8);

const sw = `/* ============================================================
   BĒSIA, sw.js   (generated by tools/build-sw.js, do not edit)

   Keeps the website and the Studio Manager working when the power
   or the network goes. Regenerated on every build.
   ============================================================ */
const VERSION = '${version}';
const CACHE = 'besia-' + VERSION;

const PRECACHE = ${JSON.stringify(precache, null, 2)};

/* The Studio Manager's shell, fetched into the cache the first time an
   admin page is opened, never on the public site. */
const ADMIN = ${JSON.stringify(adminShell, null, 2)};
const IMAGE_CACHE_MAX = 80;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One failed file must not fail the whole install. */
      .then(c => Promise.allSettled(PRECACHE.map(url => c.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  if (e.data === 'skip-waiting') self.skipWaiting();
});

/* Photographs are cached as they are seen; keep the newest eighty so
   the cache cannot grow without limit on a phone. */
function trimImages(c) {
  return c.keys().then(keys => {
    const imgs = keys.filter(k => /\\.(webp|jpe?g|png|gif|avif)$/i.test(new URL(k.url).pathname));
    const extra = imgs.length - IMAGE_CACHE_MAX;
    return extra > 0 ? Promise.all(imgs.slice(0, extra).map(k => c.delete(k))) : null;
  });
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   /* fonts and CDNs handle themselves */

  /* Films are never answered here. Safari asks for them in byte ranges
     and expects 206 replies; a cached full 200 breaks playback. They
     are also the heaviest thing on the site, not worth a cache slot. */
  if (req.headers.has('range') || /\\.(mp4|webm)$/i.test(url.pathname)) return;

  /* Pages: try the network so a fresh deploy is picked up, fall back to
     the cache when there is nothing to reach. */
  if (req.mode === 'navigate') {
    if (/\\/admin\\//.test(url.pathname)) {
      event.waitUntil(caches.open(CACHE).then(c => c.keys().then(keys => {
        const have = new Set(keys.map(k => new URL(k.url).pathname));
        const missing = ADMIN.filter(f => !have.has(new URL(f, self.location.href).pathname));
        return Promise.allSettled(missing.map(f => c.add(f)));
      })));
    }
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match('./offline.html')))
    );
    return;
  }

  /* Code and styles: network first, cache as the fallback.
     Serving a stale script against a fresh page is worse than a few
     hundred milliseconds of latency, it means a deploy lands with the
     new HTML calling into the old JavaScript, and buttons quietly stop
     working. These files are small; correctness wins. */
  if (/\\.(js|css)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  /* Everything else, images, icons, fonts, is heavy and rarely changes,
     so serve it from cache instantly and refresh in the background. */
  event.respondWith(
    caches.match(req).then(hit => {
      const net = fetch(req)
        .then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(req, copy).then(() => trimImages(c)));
          }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('sw.js written, version ' + version + ', ' + precache.length + ' files precached.');
console.log('  (' + shell.length + ' public shell files; ' + adminShell.length + ' manager files cached on first manager visit)');
